name: Migration/Azure_DevOps
on:
  push:
    branches:
    - main
jobs:
  build:
    runs-on:
      - self-hosted
      - Azure Pipelines
    steps:
    - name: checkout
      uses: actions/checkout@v4.1.0
    - name: Run a one-line script
      run: echo Hello, world!
